<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 	<meta name="keywords" content="PDS Notification">
	<title>Code verification</title>	
	<style type="text/css">
		body{
			padding: 100px;
			font-family: sans-serif;
			color: #303030;
		}

		.mail-main-content{
			/*border-radius: 20px;*/
			border: 1px solid #e0e0e0;
			padding: 50px 40px;
			box-shadow: 2px 2px 15px #d0d0d0 !important;
		}

		.text-center{
			text-align: center;
		}

		.text-right{
			text-align: right;
		}

		.text-left{
			text-align: left;
		}

		table{
			border: 1px solid #e0e0e0;
			width: 100%;
		}

		.bg-gray{
			background-color: #f0f0f0;
		}

		hr{
			background-color: red;
		}

		table,
		tr,
		th,
		td{
			border: 1px solid #e0e0e0;
			border-collapse: collapse;
			padding: 10px 20px; 
			text-align: left;
		}

		.btn{
			padding: 13px 50px;
			border-radius: 4px;
			margin: 5px;
			font-weight: bold;
		}

		.btn-primary{
			background-color: #1a73e8;
			color: #f0f0f0 !important;
			text-decoration: none; 
		}

		.btn-block{
			display: block;
		}

		.text-red{
			color: red;
		}

		.text-green{
			color: green;
		}

		.badge{
			padding: 4px 8px;
			font-weight: 12px;
			border-radius: 3px;
			font-weight: bold;
			color: #fff;
		}

		.bg-green{
			background-color: #1e8e3e;
		}

		.bg-red{
			background-color: #d93025;
		}

	</style>
</head>
<body>
	<div class="mail-main-content">
		
		<h2 class="text-center">
			<span style="font-weight: normal;">SIMS</span>
		</h2><br>

	 <div class="ibox-content" id="product_container">

                                           
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Code</th>
                            <th>Status</th>
                            <th>Mac_address</th>
                            <th>Subscriber_Code</th>
                            <th>Branch_Code</th>  
                            <th>Created_at</th>
                            <th>Updated_at</th>
                           
                        </tr>
                    </thead>
                    <tbody>


                     @forelse($emaildata['codes'] as $code)
                      
                        <tr>
                              
                            <th>{{ $code->activation_id }}</th>
                            <th>{{ $code->code }} </th>
                            <th>{{ $code->status }}</th>
                            <td>{{ $code->mac_address }}</td>
                            <td>{{ $code->subscriber_code }}</td>
                            <th>{{ $code->branch_code }}</th>
                            <th>{{ $code->created_at }}</th>
                            <th>{{ $code->updated_at }}</th>
                          
                        </tr>
                         @empty
                          <tr>
                                <th colspan="8" class="text-center text-muted"><br><br><h2> Empty </h2><br><br></th>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
			
			<p><b>--</b></p>
			<p>CEIIT-Institute of Information Systems and Technology<br>
			Visit our website: https://www.mscmarinduque.edu.ph<br>
			EMAIL: sicsDOST2022@gmail.com<br>
		</p>
			<br>
			<small>System Autogenerated email. Do not Reply.</small>
			<br><br>
			<div style="border: 1px dashed #000;"></div>
			<p style="color: #367fa9;">Rest assured that this is not a spam, a virus, nor any attempt to invade your privacy.</p>

	</div>

</body>
</html>

